# PART A - Creating a Notebook to demonstrate Numpy Operations.

1. Create an array that starts from the integer 1, ends at 20, incremented by 3.

In [7]:
import numpy as np
#Creation of array using list
list = [i for i in range(1,20,3)]

#converting array to numpy array
array = np.array(list)
print(array)

[ 1  4  7 10 13 16 19]


2. Create a new array of shape 3 with random numbers between 0 and 1.


In [10]:
array = np.random.rand(3)
print(array)

[0.80152734 0.69756185 0.96271061]


3. Create a 2 D array [[10,20,45], [30,12,16], [42,17,56]] and perform the following operations:
Slice the 2D array to get the first two rows, slice the 2D array to get the last two rows.

In [18]:
#2D Array
nparray = np.array([[10,20,45],[30,12,16],[42,17,56]])

#Slicing to get first two rows
upper_rows = nparray[:2,:]

#Slicing to get last two rows
lower_rows = nparray[1:,:]

#print upper rows
print("Upper rows :\n", + upper_rows)

#print lower rows
print("Lower rows :\n", + lower_rows)

Upper rows :
 [[10 20 45]
 [30 12 16]]
Lower rows :
 [[30 12 16]
 [42 17 56]]


4. Create two 2x2 arrays and demonstrate how you can stack the elements vertically, horizontally, and split the arrays into smaller arrays.

In [19]:
# 2x2 arrays of my choice:
a1 = np.array([[5, 6], [10, 12]])
a2 = np.array([[3, 4], [14, 16]])

# Stacking elements vertically
verticalStack = np.vstack((a1, a2))

# Stack elements horizontally
horizontalStack = np.hstack((a1, a2))

# Splitting horizontally and vertically
splitHorizontal = np.hsplit(horizontalStack, 2)
splitVertical = np.vsplit(verticalStack, 2)

# Results

#Displaying First array in order to view the stacking and splitting effectively
print("Array 1:")
print(a1)

#Displaying second array in order to view the stacking and splitting effectively
print("\nArray 2:")
print(a2)

print("\nVertically stacked:")
print(verticalStack)

print("\nHorizontally stacked:")
print(horizontalStack)

print("\nSplit horizontally:")
print(splitHorizontal)

print("\nSplit vertically:")
print(splitVertical)

Array 1:
[[ 5  6]
 [10 12]]

Array 2:
[[ 3  4]
 [14 16]]

Vertically stacked:
[[ 5  6]
 [10 12]
 [ 3  4]
 [14 16]]

Horizontally stacked:
[[ 5  6  3  4]
 [10 12 14 16]]

Split horizontally:
[array([[ 5,  6],
       [10, 12]]), array([[ 3,  4],
       [14, 16]])]

Split vertically:
[array([[ 5,  6],
       [10, 12]]), array([[ 3,  4],
       [14, 16]])]


5. Create two matrices X= ([[5, 7, 2], [4, 5, 6], [7, 4 ,2]]) Y= ([[4, 2], [6, 2], [4, 2]]),
Is it possible to multiply these matrices?
Demonstrate the case when it is not possible to.

-> We can only multiply the matrices if the number of columns of matrix X are equal to number of rows of matrix Y. According to the given two matrices, matrix X has dimensions 3X3 and matrix Y has dimensions 3X2. Hence, it is seen that the number of Columns in matrix X is equal to number of rows in matrix Y, hence the multiplication is possible. But, if the matrix X is 3X3 dimensional and matrix Y is 2X3 dimensional, then the result of multiplication of X x Y matrices is Matrix Z which will be 3X2, where the multiplication is not possible.

In [28]:
# Matrix X and Y
X = np.array([[5,7,2],
              [4,5,6],
              [7,4,2]])

Y = np.array([[4,2],
              [6,2],
              [4,2]])

#Checking the possibility of multiplication

# The below given command will give number of columns and number of rows in X and Y
cols_X = X.shape[1]
rows_Y = Y.shape[0]

#Multiplication
if cols_X == rows_Y:
    result = np.dot(X,Y)

    print("Multiplication is possible: \n",result)
else:
    print("Multiplication is not possible")
    


Multiplication is possible: 
 [[70 28]
 [70 30]
 [60 26]]


In [29]:
#Now lets see if 3x3 dimensional and 2x3 dimensional matrices can be multiplied.
X = np.array([[5,7,2],[4,5,6]])
Y = np.array([[4,2],[6,2]])

#Checking the possibility of multiplication

# The below given command will give number of columns and number of rows in X and Y
cols_X = X.shape[1]
rows_Y = Y.shape[0]

#Multiplication
if cols_X == rows_Y:
    result = np.dot(X,Y)

    print("Multiplication is possible: \n",result)
else:
    print("Multiplication is not possible")

Multiplication is not possible


6. Create two arrays, x = ([2, -1, -8]) y = ([3, 1, -2]). Find the Shape, Number of dimensions of vector x. Reshape the vector x to a matrix of size (3,1) and determine the number of dimensions after reshaping y to a matrix of (3,1).

In [30]:
# Arrays x and y
x = np.array([2, -1, -8])
y = np.array([3, 1, -2])

# Find the shape and number of dimensions of vector x
shape_of_x = x.shape
#The above line of code returns the shape of the array x, which is (3,), i.e 1D array with 3 elements.

dimensions_of_x = x.ndim
#The above code returns the number of dimensions of x, i.e 1.

# Reshaping x to matrix of size (3, 1)
#x.reshape((3, 1)) will reshape x into a 2D array with dimensions (3, 1).
xReshaped = x.reshape((3, 1))

# Reshape y to a matrix of size (3, 1)
#y.reshape((3, 1)) will reshape y into a 2D array with dimensions (3, 1).
yReshaped = y.reshape((3, 1))

# Determine the number of dimensions after reshaping y
yReshapedDimensions = yReshaped.ndim
#yReshaped.ndim returns the number of dimensions of the reshaped y, which is 2

print("x: \n",x)

print(f"Shape of x: {shape_of_x}")
print(f"Number of dimensions of x: {dimensions_of_x}")

print("\nReshaped x:")
print(xReshaped)

print("\nReshaped y:")
print(yReshaped)
print(f"Number of dimensions of reshaped y: {yReshapedDimensions}")

x: 
 [ 2 -1 -8]
Shape of x: (3,)
Number of dimensions of x: 1

Reshaped x:
[[ 2]
 [-1]
 [-8]]

Reshaped y:
[[ 3]
 [ 1]
 [-2]]
Number of dimensions of reshaped y: 2


7. How does broadcasting work? Demonstrate the subtraction, multiplication by considering a 3 x 3 matrix

-> Broadcasting in NumPy allows arrays having different shapes to combine together in order to perform arithmetic operations. It implicitly expands the smaller array to match with the shape of larger array in order to perform the element-wise operation.

In [38]:
# Broadcasting with subtraction and multiplication of a 3x3 matrix:
# Create 3x3 matrix
X = np.array([[11, 12, 13],
              [14, 15, 16],
              [17, 18, 19]])

# Define a 1D array (row vector)
Y = np.array([10, 20, 30])

# Define a 1D array (column vector)
Z = np.array([4, 5, 6]).reshape(-1, 1)

# Broadcasting with subtraction
Subtraction = X - Y

# Broadcasting with multiplication
Multiplication = X * Z

print("X : \n",X,"\n")
print("Y : \n",Y,"\n")
print("Z : \n",Z,"\n")

print("Subtraction (X - Y): \n",Subtraction,"\n")

print("Multiplication (X * Z): \n",Multiplication,"\n")

X : 
 [[11 12 13]
 [14 15 16]
 [17 18 19]] 

Y : 
 [10 20 30] 

Z : 
 [[4]
 [5]
 [6]] 

Subtraction (X - Y): 
 [[  1  -8 -17]
 [  4  -5 -14]
 [  7  -2 -11]] 

Multiplication (X * Z): 
 [[ 44  48  52]
 [ 70  75  80]
 [102 108 114]] 



# Part B- Linear Equations

1. Determine the singularity of the system of equations, comment on the expected solution of the system. Solve the system of equations if possible.
Justify the reason why you believe the system can or cannot be solved using numpy functions.

Part B.1

4x + y - 2z = 10

2x - 3y + 2z = -4

x + 2y +  = 6



-> In order to determine the singularity of the system, we analyze the determinant of the coefficient matrix. If the determinant is non-zero and the system is non-singular, it will have a unique solution. In case the determinant is zero, the system may be singular having no solutions or the system may have infinite solutions.

In [43]:
# Coefficient of Matrix X
X = np.array([[4,1,-2],
              [2,-3,2],
              [1,2,3]])

#Constant vector Y
Y = np.array([10,-4,6])

#Determinant of X

detX = np.linalg.det(X)

#Solving Z with numpy Linear Algebra
if detX !=0:
    Z = np.linalg.solve(X,Y)
    print("It is a non-singular system hence there is a unique solution:")
    print(f"x ={Z[0]},y={Z[1]},z={[2]}")
else:
    print("This may be a singular system or there might be no infinite solutions")

It is a non-singular system hence there is a unique solution:
x =1.7999999999999998,y=2.4,z=[2]


Part B.2

2x - y + 3z + 4w = 10

4x - 2y + 6z + 8w = 20

3x + y - 2z + 2w = 3

x + 3y - 4z + w = -1

In [44]:
# Coefficient of Matrix X
X = np.array([[2,-1,3,4],
              [4,-2,6,8],
              [3,1,-2,2],
              [1,3,-4,1]])

#Constant vector Y
Y = np.array([10,20,3,-1])

#Determinant of X

detX = np.linalg.det(X)

#Solving Z with numpy Linear Algebra
if detX !=0:
    Z = np.linalg.solve(X,Y)
    print("It is a non-singular system hence there is a unique solution:")
    print(f"x ={Z[0]},y={Z[1]},z={[2]},w={[3]}")
else:
    print("This may be a singular system or there might be no infinite solutions")

This may be a singular system or there might be no infinite solutions
